### PR TITLE
Toggle night when you click the night-toggle-icon

### PR DESCRIPTION
**Pull request by siddharthkp**
I'm sorry, it rubbed me the wrong way that you can toggle night with a switch on the home page but not from the icon that's built for that in the preview

twizzy

### CODE REVIEW

**Comment by kitze** [comment]
@siddharthkp lol but now this full moon is driving me crazy, in the actual app it switches to an empty moon with outline in light mode 😛️

**Comment by kitze** [comment]
eh fuck it @siddharthkp

**Comment by kitze** [comment]
tnx!

**Comment by siddharthkp** [comment]
Err, can you add the right icon to the repo, I'll take it from there

**Pull request merged**
